// Renders a shareable PNG of the Smith-Kerns pressure summary so the
// operator can paste it into WhatsApp / Slack / email. All drawing is
// done with the Canvas 2D API — no extra dependencies, no DOM scraping.
//
// Layout (1200 x 800):
//   ┌─────────────────────────────────────────────────────────────┐
//   │ Ganton G3                                4 May 2026         │
//   │ Dollar spot pressure                                        │
//   │  ┌──────────┐ ┌──────────────┐ ┌──────────────┐             │
//   │  │  42%     │ │  58%  8 May  │ │ 7 images     │             │
//   │  │  Today   │ │  Peak (14d)  │ │ 4.2% disease │             │
//   │  │  Mod.    │ │  High        │ │ avg coverage │             │
//   │  └──────────┘ └──────────────┘ └──────────────┘             │
//   │ [ ─────── 30d history + 14d forecast (dashed) ────── ]      │
//   │ Generated by Dollar Spot Monitor                            │
//   └─────────────────────────────────────────────────────────────┘

import type { PressureScore } from "./airtable";
import type { ForecastPressureRow } from "./forecast-pressure";

export type ShareCardInput = {
  locationName: string;
  /** Optional public URL of the location's own logo. */
  locationLogoUrl?: string | null;
  scores: PressureScore[];
  forecast: ForecastPressureRow[];
  photoCount: number;
  meanDiseasePct: number | null;
  photoDates: string[];
};

const W = 1200;
const H = 800;
const SCALE = 2; // 2400 x 1600 actual pixels for retina

const TEMP = "#d97706";
const RH = "#0284c7";
const PRESSURE = "#374151";
const FORECAST = "#9ca3af";
const PHOTO = "#0284c7";

export async function buildShareCard(input: ShareCardInput): Promise<Blob> {
  const canvas = document.createElement("canvas");
  canvas.width = W * SCALE;
  canvas.height = H * SCALE;
  const ctx = canvas.getContext("2d");
  if (!ctx) throw new Error("Canvas 2D not available");
  ctx.scale(SCALE, SCALE);
  ctx.imageSmoothingEnabled = true;

  // Best-effort logo loads — if any fails we still produce a valid card.
  const [striLogo, locationLogo] = await Promise.all([
    loadImage("/stri-logo.png").catch(() => null),
    input.locationLogoUrl
      ? loadImage(input.locationLogoUrl).catch(() => null)
      : Promise.resolve(null),
  ]);

  drawBackground(ctx);
  drawHeader(ctx, input, striLogo, locationLogo);
  drawStatTiles(ctx, input);
  drawChart(ctx, input);
  drawFooter(ctx);

  return new Promise((resolve, reject) => {
    canvas.toBlob(
      (b) => (b ? resolve(b) : reject(new Error("toBlob returned null"))),
      "image/png"
    );
  });
}

function loadImage(src: string): Promise<HTMLImageElement> {
  return new Promise((resolve, reject) => {
    const img = new Image();
    img.crossOrigin = "anonymous";
    img.onload = () => resolve(img);
    img.onerror = () => reject(new Error(`failed to load ${src}`));
    img.src = src;
  });
}

function drawBackground(ctx: CanvasRenderingContext2D) {
  ctx.fillStyle = "#ffffff";
  ctx.fillRect(0, 0, W, H);
}

function drawHeader(
  ctx: CanvasRenderingContext2D,
  input: ShareCardInput,
  striLogo: HTMLImageElement | null,
  locationLogo: HTMLImageElement | null
) {
  // Left side: optional location logo, then location name + subline.
  let textX = 40;
  if (locationLogo && locationLogo.naturalWidth && locationLogo.naturalHeight) {
    const targetH = 56;
    const ratio = locationLogo.naturalWidth / locationLogo.naturalHeight;
    const drawW = targetH * ratio;
    ctx.drawImage(locationLogo, 40, 28, drawW, targetH);
    textX = 40 + drawW + 16;
  }
  ctx.fillStyle = "#1c1917";
  ctx.font = "bold 32px ui-sans-serif, system-ui, -apple-system, sans-serif";
  ctx.textAlign = "left";
  ctx.textBaseline = "top";
  ctx.fillText(input.locationName, textX, 32);
  ctx.fillStyle = "#57534e";
  ctx.font = "16px ui-sans-serif, system-ui, sans-serif";
  ctx.fillText("Dollar spot pressure", textX, 72);

  // Right side: STRI logo (if loaded) above the generated-on date.
  const today = new Date();
  const dateStr = today.toLocaleDateString("en-GB", {
    day: "numeric",
    month: "long",
    year: "numeric",
  });

  if (striLogo && striLogo.naturalWidth && striLogo.naturalHeight) {
    const targetH = 56;
    const ratio = striLogo.naturalWidth / striLogo.naturalHeight;
    const drawW = targetH * ratio;
    const x = W - 40 - drawW;
    const y = 24;
    ctx.drawImage(striLogo, x, y, drawW, targetH);
    ctx.fillStyle = "#78716c";
    ctx.font = "13px ui-sans-serif, system-ui, sans-serif";
    ctx.textAlign = "right";
    ctx.fillText(`Generated ${dateStr}`, W - 40, y + targetH + 6);
  } else {
    ctx.textAlign = "right";
    ctx.fillStyle = "#78716c";
    ctx.font = "14px ui-sans-serif, system-ui, sans-serif";
    ctx.fillText(`Generated ${dateStr}`, W - 40, 36);
  }
}

function bandColours(band: string): { bg: string; border: string; fg: string } {
  if (band === "High") return { bg: "#fef2f2", border: "#fca5a5", fg: "#991b1b" };
  if (band === "Moderate")
    return { bg: "#fffbeb", border: "#fcd34d", fg: "#92400e" };
  return { bg: "#f0fdf4", border: "#86efac", fg: "#166534" };
}

function drawStatTiles(ctx: CanvasRenderingContext2D, input: ShareCardInput) {
  const tileY = 110;
  const tileH = 160;
  const gap = 16;
  const totalW = W - 80;
  const tileW = (totalW - gap * 2) / 3;

  const latest = input.scores[input.scores.length - 1];
  const peak = pickPeak(input.forecast);

  drawTile(ctx, 40, tileY, tileW, tileH, {
    bg: latest ? bandColours(latest.risk_band).bg : "#f5f5f4",
    border: latest ? bandColours(latest.risk_band).border : "#d6d3d1",
    label: "Today",
    big: latest
      ? `${(latest.smith_kerns_probability * 100).toFixed(0)}%`
      : "—",
    sub: latest
      ? `${formatShortDate(latest.date)} · ${latest.risk_band}`
      : "no data",
    fg: latest ? bandColours(latest.risk_band).fg : "#44403c",
  });

  drawTile(ctx, 40 + tileW + gap, tileY, tileW, tileH, {
    bg: peak ? bandColours(peak.risk_band).bg : "#f5f5f4",
    border: peak ? bandColours(peak.risk_band).border : "#d6d3d1",
    label: "Peak in next 14 days",
    big: peak ? `${(peak.probability * 100).toFixed(0)}%` : "—",
    sub: peak
      ? `${formatShortDate(peak.date)} · ${peak.risk_band}`
      : "no forecast",
    fg: peak ? bandColours(peak.risk_band).fg : "#44403c",
  });

  drawTile(ctx, 40 + (tileW + gap) * 2, tileY, tileW, tileH, {
    bg: "#f0f9ff",
    border: "#7dd3fc",
    label: "Photos assessed",
    big: String(input.photoCount),
    sub:
      input.meanDiseasePct != null
        ? `${input.meanDiseasePct.toFixed(1)}% mean disease coverage`
        : "no photos yet",
    fg: "#075985",
  });
}

function drawTile(
  ctx: CanvasRenderingContext2D,
  x: number,
  y: number,
  w: number,
  h: number,
  spec: { bg: string; border: string; label: string; big: string; sub: string; fg: string }
) {
  // Rounded rect background + 2px border
  roundRect(ctx, x, y, w, h, 12);
  ctx.fillStyle = spec.bg;
  ctx.fill();
  ctx.lineWidth = 2;
  ctx.strokeStyle = spec.border;
  ctx.stroke();

  // Centre everything horizontally inside the tile so the layout matches
  // the dashboard.
  const cx = x + w / 2;
  ctx.textAlign = "center";
  ctx.textBaseline = "top";
  ctx.fillStyle = spec.fg;
  ctx.font = "bold 12px ui-sans-serif, system-ui, sans-serif";
  ctx.fillText(spec.label.toUpperCase(), cx, y + 18);

  ctx.font = "bold 56px ui-sans-serif, system-ui, sans-serif";
  ctx.fillText(spec.big, cx, y + 50);

  ctx.font = "14px ui-sans-serif, system-ui, sans-serif";
  ctx.fillText(spec.sub, cx, y + h - 30);
}

function drawChart(ctx: CanvasRenderingContext2D, input: ShareCardInput) {
  const top = 300;
  const bottom = 720;
  const left = 60;
  const right = W - 40;
  const chartW = right - left;
  const chartH = bottom - top;

  // X axis: combine scores + forecast (dedup). Each entry has date + value.
  type Pt = {
    date: string;
    value: number;
    isForecast: boolean;
  };
  const points: Pt[] = [];
  for (const s of input.scores) {
    points.push({
      date: s.date,
      value: s.smith_kerns_probability,
      isForecast: false,
    });
  }
  for (const f of input.forecast) {
    points.push({
      date: f.date,
      value: f.smith_kerns_probability,
      isForecast: true,
    });
  }
  if (points.length === 0) {
    ctx.fillStyle = "#a8a29e";
    ctx.font = "14px ui-sans-serif, system-ui, sans-serif";
    ctx.textAlign = "center";
    ctx.fillText("No pressure data to chart yet", (left + right) / 2, top + chartH / 2);
    return;
  }
  points.sort((a, b) => a.date.localeCompare(b.date));

  const xFor = (i: number) =>
    points.length === 1
      ? left + chartW / 2
      : left + (i / (points.length - 1)) * chartW;
  // Y-axis caps at 60% by default to match the dashboard, but auto-grows
  // if any value exceeds it so we never hide a spike.
  const observedMax = points.reduce((m, p) => Math.max(m, p.value), 0);
  const yMax = Math.max(0.6, observedMax * 1.1);
  const yFor = (v: number) => bottom - (v / yMax) * chartH;

  // Risk-band shading — translucent washes to match the dashboard.
  ctx.fillStyle = "rgba(34, 197, 94, 0.12)"; // green-500 @ 12%
  ctx.fillRect(left, yFor(0.2), chartW, bottom - yFor(0.2));
  ctx.fillStyle = "rgba(245, 158, 11, 0.18)"; // amber-500 @ 18%
  ctx.fillRect(left, yFor(0.3), chartW, yFor(0.2) - yFor(0.3));
  ctx.fillStyle = "rgba(239, 68, 68, 0.22)"; // red-500 @ 22%
  ctx.fillRect(left, top, chartW, yFor(0.3) - top);

  // Y-axis ticks: every 10% from 0 up to yMax (rounded up).
  ctx.fillStyle = "#78716c";
  ctx.font = "12px ui-sans-serif, system-ui, sans-serif";
  ctx.textAlign = "right";
  ctx.textBaseline = "middle";
  const tickStep = 0.1;
  for (let v = 0; v <= yMax + 1e-9; v += tickStep) {
    ctx.fillText(`${Math.round(v * 100)}%`, left - 6, yFor(v));
    ctx.beginPath();
    ctx.strokeStyle = "rgba(0,0,0,0.06)";
    ctx.lineWidth = 1;
    ctx.moveTo(left, yFor(v));
    ctx.lineTo(right, yFor(v));
    ctx.stroke();
  }

  // Axis frame
  ctx.strokeStyle = "#e7e5e4";
  ctx.lineWidth = 1;
  ctx.strokeRect(left, top, chartW, chartH);

  // Find boundary index between actual and forecast (last actual)
  let lastActual = -1;
  for (let i = 0; i < points.length; i++) {
    if (!points[i].isForecast) lastActual = i;
  }

  // Actual line (solid)
  if (lastActual >= 0) {
    ctx.beginPath();
    ctx.strokeStyle = PRESSURE;
    ctx.lineWidth = 3;
    ctx.setLineDash([]);
    for (let i = 0; i <= lastActual; i++) {
      const x = xFor(i);
      const y = yFor(points[i].value);
      if (i === 0) ctx.moveTo(x, y);
      else ctx.lineTo(x, y);
    }
    ctx.stroke();
  }

  // Forecast line (dashed) — bridge from last actual into forecast
  const forecastStart = lastActual >= 0 ? lastActual : 0;
  if (forecastStart < points.length - 1) {
    ctx.beginPath();
    ctx.strokeStyle = FORECAST;
    ctx.lineWidth = 3;
    ctx.setLineDash([8, 6]);
    for (let i = forecastStart; i < points.length; i++) {
      const x = xFor(i);
      const y = yFor(points[i].value);
      if (i === forecastStart) ctx.moveTo(x, y);
      else ctx.lineTo(x, y);
    }
    ctx.stroke();
    ctx.setLineDash([]);
  }

  // Today: dashed vertical line + a styled date pill at the top with a
  // small downward arrow into the line. Replaces the old plain "Today"
  // text label so the dotted line is anchored to a clear date.
  if (lastActual >= 0) {
    const tx = xFor(lastActual);
    // Dashed line
    ctx.beginPath();
    ctx.strokeStyle = "#1c1917";
    ctx.lineWidth = 1.5;
    ctx.setLineDash([4, 4]);
    ctx.moveTo(tx, top);
    ctx.lineTo(tx, bottom);
    ctx.stroke();
    ctx.setLineDash([]);
    // Date pill (rounded rect with the actual date + arrow)
    const dateStr = formatShortDate(points[lastActual].date);
    ctx.font = "bold 13px ui-sans-serif, system-ui, sans-serif";
    const padX = 10;
    const textW = ctx.measureText(dateStr).width;
    const pillW = textW + padX * 2;
    const pillH = 24;
    const pillX = tx - pillW / 2;
    const pillY = top + 4;
    roundRect(ctx, pillX, pillY, pillW, pillH, 6);
    ctx.fillStyle = "#1c1917";
    ctx.fill();
    // Downward arrow tip pointing into the dashed line
    ctx.beginPath();
    ctx.moveTo(tx - 6, pillY + pillH);
    ctx.lineTo(tx + 6, pillY + pillH);
    ctx.lineTo(tx, pillY + pillH + 6);
    ctx.closePath();
    ctx.fill();
    // Date text
    ctx.fillStyle = "#ffffff";
    ctx.textAlign = "center";
    ctx.textBaseline = "middle";
    ctx.fillText(dateStr, tx, pillY + pillH / 2);
  }

  // Photo markers — map-pin shape with the count inside, tip pointing
  // down at the chart axis. The pin's tip sits at `pinTipY` and the body
  // extends ~44px upward; we lower the tip from the chart top so the pin
  // fits cleanly inside the chart area.
  const countByDate = new Map<string, number>();
  for (const d of input.photoDates) {
    countByDate.set(d, (countByDate.get(d) ?? 0) + 1);
  }
  const pinTipY = top + 50;
  for (let i = 0; i < points.length; i++) {
    const count = countByDate.get(points[i].date);
    if (!count) continue;
    const x = xFor(i);
    const path = new Path2D(
      `M ${x} ${pinTipY} L ${x - 11} ${pinTipY - 16} A 16 16 0 1 1 ${
        x + 11
      } ${pinTipY - 16} Z`
    );
    ctx.fillStyle = PHOTO;
    ctx.fill(path);
    ctx.lineWidth = 2.5;
    ctx.strokeStyle = "#ffffff";
    ctx.stroke(path);
    ctx.fillStyle = "#ffffff";
    ctx.font = "bold 16px ui-sans-serif, system-ui, sans-serif";
    ctx.textAlign = "center";
    ctx.textBaseline = "middle";
    ctx.fillText(count > 9 ? "9+" : String(count), x, pinTipY - 28);
  }

  // X-axis labels — sparse, evenly-spaced including the first and last
  // points. Today is no longer added here (its date is on the pill at
  // the top of the dashed line) so we don't double-up close to the stride
  // ticks. Labels are angled -30° so they don't overlap on dense ranges.
  const labelIxs = new Set<number>([0, points.length - 1]);
  const stride = Math.max(1, Math.floor(points.length / 6));
  for (let i = 0; i < points.length; i += stride) labelIxs.add(i);

  ctx.fillStyle = "#57534e";
  ctx.font = "11px ui-sans-serif, system-ui, sans-serif";
  for (const i of labelIxs) {
    ctx.save();
    ctx.translate(xFor(i), bottom + 8);
    ctx.rotate(-Math.PI / 6); // -30°
    ctx.textAlign = "right";
    ctx.textBaseline = "middle";
    ctx.fillText(formatShortDate(points[i].date), 0, 0);
    ctx.restore();
  }

  // Tiny inline legend
  const legendY = bottom + 28;
  let lx = left;
  ctx.font = "12px ui-sans-serif, system-ui, sans-serif";
  ctx.textBaseline = "middle";
  ctx.textAlign = "left";

  // actual
  ctx.beginPath();
  ctx.strokeStyle = PRESSURE;
  ctx.lineWidth = 3;
  ctx.moveTo(lx, legendY);
  ctx.lineTo(lx + 24, legendY);
  ctx.stroke();
  ctx.fillStyle = "#1c1917";
  ctx.fillText("Actual", lx + 30, legendY);
  lx += 100;

  // forecast
  ctx.beginPath();
  ctx.strokeStyle = FORECAST;
  ctx.lineWidth = 3;
  ctx.setLineDash([8, 6]);
  ctx.moveTo(lx, legendY);
  ctx.lineTo(lx + 24, legendY);
  ctx.stroke();
  ctx.setLineDash([]);
  ctx.fillStyle = "#1c1917";
  ctx.fillText("14-day forecast", lx + 30, legendY);
  lx += 160;

  // photo dot
  ctx.beginPath();
  ctx.fillStyle = PHOTO;
  ctx.arc(lx + 8, legendY, 6, 0, Math.PI * 2);
  ctx.fill();
  ctx.fillStyle = "#1c1917";
  ctx.fillText("Photo assessed", lx + 22, legendY);
}

function drawFooter(ctx: CanvasRenderingContext2D, h = H) {
  ctx.fillStyle = "#a8a29e";
  ctx.font = "11px ui-sans-serif, system-ui, sans-serif";
  ctx.textAlign = "right";
  ctx.textBaseline = "bottom";
  ctx.fillText(
    "Smith-Kerns logistic-regression model · Dollar Spot Monitor · STRI",
    W - 40,
    h - 20
  );
}

// =====================================================================
// Phase plot share card
// =====================================================================

import { smithKerns } from "./smith-kerns";

const PHASE_T_MIN = 5;
const PHASE_T_MAX = 35;
const PHASE_T_STEP = 1;
const PHASE_T_CELLS = (PHASE_T_MAX - PHASE_T_MIN) / PHASE_T_STEP;
const PHASE_RH_MIN = 40;
const PHASE_RH_MAX = 100;
const PHASE_RH_STEP = 5;
const PHASE_RH_CELLS = (PHASE_RH_MAX - PHASE_RH_MIN) / PHASE_RH_STEP;
const PHASE_HISTORY_DAYS = 30;

function phaseBandFill(p: number): string {
  if (p < 0.2) return "#dcfce7";
  if (p < 0.3) return "#fef3c7";
  return "#fecaca";
}
function pastOpacity(i: number, n: number): number {
  if (n <= 1) return 1;
  return 0.15 + 0.85 * (i / (n - 1));
}
function futureOpacity(i: number, n: number): number {
  if (n <= 1) return 1;
  return 1 - 0.55 * (i / (n - 1));
}

export type PhaseShareCardInput = {
  locationName: string;
  locationLogoUrl?: string | null;
  scores: PressureScore[];
  forecast: ForecastPressureRow[];
  photoCount: number;
  meanDiseasePct: number | null;
};

export async function buildPhaseShareCard(
  input: PhaseShareCardInput
): Promise<Blob> {
  const PW = 1200;
  const PH = 950;
  const SCALE_LOCAL = 2;
  const canvas = document.createElement("canvas");
  canvas.width = PW * SCALE_LOCAL;
  canvas.height = PH * SCALE_LOCAL;
  const ctx = canvas.getContext("2d");
  if (!ctx) throw new Error("Canvas 2D not available");
  ctx.scale(SCALE_LOCAL, SCALE_LOCAL);
  ctx.imageSmoothingEnabled = true;

  const [striLogo, locationLogo] = await Promise.all([
    loadImage("/stri-logo.png").catch(() => null),
    input.locationLogoUrl
      ? loadImage(input.locationLogoUrl).catch(() => null)
      : Promise.resolve(null),
  ]);

  // Background
  ctx.fillStyle = "#ffffff";
  ctx.fillRect(0, 0, PW, PH);

  // Header — share the same drawHeader logic as the line-chart card so the
  // location/STRI/date sit identically.
  drawHeader(
    ctx,
    {
      locationName: input.locationName,
      locationLogoUrl: input.locationLogoUrl ?? null,
      scores: input.scores,
      forecast: input.forecast,
      photoCount: input.photoCount,
      meanDiseasePct: input.meanDiseasePct,
      photoDates: [],
    },
    striLogo,
    locationLogo
  );

  // Stat tiles
  drawStatTiles(ctx, {
    locationName: input.locationName,
    locationLogoUrl: input.locationLogoUrl ?? null,
    scores: input.scores,
    forecast: input.forecast,
    photoCount: input.photoCount,
    meanDiseasePct: input.meanDiseasePct,
    photoDates: [],
  });

  // Phase grid area — slot it under the tiles, leaving room for the footer.
  const gridLeft = 60;
  const gridRight = PW - 40;
  const gridTop = 300;
  const gridBottom = PH - 70;
  const innerW = gridRight - gridLeft;
  const innerH = gridBottom - gridTop;
  const cellW = innerW / PHASE_T_CELLS;
  const cellH = innerH / PHASE_RH_CELLS;

  function tToX(t: number): number {
    const c = Math.max(PHASE_T_MIN, Math.min(PHASE_T_MAX, t));
    return gridLeft + ((c - PHASE_T_MIN) / (PHASE_T_MAX - PHASE_T_MIN)) * innerW;
  }
  function rhToY(rh: number): number {
    const c = Math.max(PHASE_RH_MIN, Math.min(PHASE_RH_MAX, rh));
    return (
      gridTop + ((PHASE_RH_MAX - c) / (PHASE_RH_MAX - PHASE_RH_MIN)) * innerH
    );
  }

  // Cells
  for (let ri = 0; ri < PHASE_RH_CELLS; ri++) {
    const rhCenter = PHASE_RH_MAX - (ri + 0.5) * PHASE_RH_STEP;
    for (let ti = 0; ti < PHASE_T_CELLS; ti++) {
      const tCenter = PHASE_T_MIN + (ti + 0.5) * PHASE_T_STEP;
      const r = smithKerns(tCenter, rhCenter);
      const x = gridLeft + ti * cellW;
      const y = gridTop + ri * cellH;
      ctx.fillStyle = phaseBandFill(r.probability);
      ctx.fillRect(x, y, cellW + 0.5, cellH + 0.5);
      ctx.fillStyle = "rgba(28,25,23,0.55)";
      ctx.font = "500 11px ui-sans-serif, system-ui, sans-serif";
      ctx.textAlign = "center";
      ctx.textBaseline = "middle";
      ctx.fillText(
        String(Math.round(r.probability * 100)),
        x + cellW / 2,
        y + cellH / 2
      );
    }
  }

  // Frame
  ctx.strokeStyle = "rgba(28,25,23,0.3)";
  ctx.lineWidth = 1;
  ctx.strokeRect(gridLeft, gridTop, innerW, innerH);

  // Y axis ticks (RH)
  ctx.font = "12px ui-sans-serif, system-ui, sans-serif";
  ctx.fillStyle = "#57534e";
  ctx.textAlign = "right";
  ctx.textBaseline = "middle";
  for (let rh = PHASE_RH_MIN; rh <= PHASE_RH_MAX; rh += 10) {
    const y = rhToY(rh);
    ctx.fillText(`${rh}%`, gridLeft - 6, y);
    ctx.beginPath();
    ctx.strokeStyle = "rgba(28,25,23,0.4)";
    ctx.moveTo(gridLeft - 4, y);
    ctx.lineTo(gridLeft, y);
    ctx.stroke();
  }
  // Y label rotated
  ctx.save();
  ctx.translate(20, gridTop + innerH / 2);
  ctx.rotate(-Math.PI / 2);
  ctx.fillStyle = "#1c1917";
  ctx.font = "bold 12px ui-sans-serif, system-ui, sans-serif";
  ctx.textAlign = "center";
  ctx.textBaseline = "middle";
  ctx.fillText("5-day mean humidity (%)", 0, 0);
  ctx.restore();

  // X axis ticks (T)
  ctx.fillStyle = "#57534e";
  ctx.font = "12px ui-sans-serif, system-ui, sans-serif";
  ctx.textAlign = "center";
  ctx.textBaseline = "top";
  for (let t = PHASE_T_MIN; t <= PHASE_T_MAX; t += 5) {
    const x = tToX(t);
    ctx.fillText(`${t}°C`, x, gridBottom + 6);
    ctx.beginPath();
    ctx.strokeStyle = "rgba(28,25,23,0.4)";
    ctx.moveTo(x, gridBottom);
    ctx.lineTo(x, gridBottom + 4);
    ctx.stroke();
  }
  // X label
  ctx.fillStyle = "#1c1917";
  ctx.font = "bold 12px ui-sans-serif, system-ui, sans-serif";
  ctx.textAlign = "center";
  ctx.fillText(
    "5-day mean temperature (°C)",
    gridLeft + innerW / 2,
    gridBottom + 30
  );

  // Trail data
  const last = input.scores.slice(-PHASE_HISTORY_DAYS);
  const next = input.forecast;
  const today = last[last.length - 1];

  // Forecast trail (drawn first so today dot lands on top)
  const futureChain = today
    ? [
        {
          t: today.temp_5day_avg_c,
          rh: today.rh_5day_avg_pct,
        },
        ...next.map((f) => ({
          t: f.temp_5day_avg_c,
          rh: f.rh_5day_avg_pct,
        })),
      ]
    : next.map((f) => ({
        t: f.temp_5day_avg_c,
        rh: f.rh_5day_avg_pct,
      }));
  ctx.lineWidth = 3;
  ctx.lineCap = "round";
  ctx.setLineDash([8, 5]);
  for (let i = 0; i < futureChain.length - 1; i++) {
    const a = futureChain[i];
    const b = futureChain[i + 1];
    const opa =
      (futureOpacity(Math.max(0, i), Math.max(1, next.length)) +
        futureOpacity(Math.max(0, i), Math.max(1, next.length))) /
      2;
    ctx.strokeStyle = `rgba(156,163,175,${opa})`;
    ctx.beginPath();
    ctx.moveTo(tToX(a.t), rhToY(a.rh));
    ctx.lineTo(tToX(b.t), rhToY(b.rh));
    ctx.stroke();
  }
  ctx.setLineDash([]);
  for (let i = 0; i < next.length; i++) {
    const f = next[i];
    const op = futureOpacity(i, next.length);
    ctx.beginPath();
    ctx.fillStyle = `rgba(156,163,175,${op})`;
    ctx.arc(tToX(f.temp_5day_avg_c), rhToY(f.rh_5day_avg_pct), 4, 0, Math.PI * 2);
    ctx.fill();
    ctx.lineWidth = 1.5;
    ctx.strokeStyle = "#ffffff";
    ctx.stroke();
  }

  // Past trail with fading segments
  ctx.lineWidth = 3;
  for (let i = 0; i < last.length - 1; i++) {
    const a = last[i];
    const b = last[i + 1];
    const opa =
      (pastOpacity(i, last.length) + pastOpacity(i + 1, last.length)) / 2;
    ctx.strokeStyle = `rgba(28,25,23,${opa})`;
    ctx.beginPath();
    ctx.moveTo(tToX(a.temp_5day_avg_c), rhToY(a.rh_5day_avg_pct));
    ctx.lineTo(tToX(b.temp_5day_avg_c), rhToY(b.rh_5day_avg_pct));
    ctx.stroke();
  }
  for (let i = 0; i < last.length; i++) {
    const s = last[i];
    const op = pastOpacity(i, last.length);
    ctx.beginPath();
    ctx.fillStyle = `rgba(28,25,23,${op})`;
    ctx.arc(tToX(s.temp_5day_avg_c), rhToY(s.rh_5day_avg_pct), 4, 0, Math.PI * 2);
    ctx.fill();
    ctx.lineWidth = 1.5;
    ctx.strokeStyle = `rgba(255,255,255,${op})`;
    ctx.stroke();
  }

  // Today emphasised
  if (today) {
    const tx = tToX(today.temp_5day_avg_c);
    const ty = rhToY(today.rh_5day_avg_pct);
    ctx.beginPath();
    ctx.fillStyle = "#1c1917";
    ctx.arc(tx, ty, 11, 0, Math.PI * 2);
    ctx.fill();
    ctx.lineWidth = 4;
    ctx.strokeStyle = "#ffffff";
    ctx.stroke();
    ctx.fillStyle = "#1c1917";
    ctx.font = "bold 13px ui-sans-serif, system-ui, sans-serif";
    ctx.textAlign = "left";
    ctx.textBaseline = "middle";
    ctx.fillText("Today", tx + 16, ty - 10);
  }

  // Footer at the bottom of the taller phase canvas
  drawFooter(ctx, PH);

  return new Promise((resolve, reject) => {
    canvas.toBlob(
      (b) => (b ? resolve(b) : reject(new Error("toBlob returned null"))),
      "image/png"
    );
  });
}

function pickPeak(
  forecast: ForecastPressureRow[]
): { date: string; probability: number; risk_band: string } | null {
  if (forecast.length === 0) return null;
  let best = forecast[0];
  for (const f of forecast) {
    if (f.smith_kerns_probability > best.smith_kerns_probability) best = f;
  }
  return {
    date: best.date,
    probability: best.smith_kerns_probability,
    risk_band: best.risk_band,
  };
}

function formatShortDate(iso: string): string {
  const d = new Date(`${iso}T00:00:00Z`);
  return d.toLocaleDateString("en-GB", {
    day: "numeric",
    month: "short",
    timeZone: "UTC",
  });
}

function roundRect(
  ctx: CanvasRenderingContext2D,
  x: number,
  y: number,
  w: number,
  h: number,
  r: number
) {
  ctx.beginPath();
  ctx.moveTo(x + r, y);
  ctx.arcTo(x + w, y, x + w, y + h, r);
  ctx.arcTo(x + w, y + h, x, y + h, r);
  ctx.arcTo(x, y + h, x, y, r);
  ctx.arcTo(x, y, x + w, y, r);
  ctx.closePath();
}

// Try clipboard.write first, fall back to a download.
export async function copyOrDownloadBlob(
  blob: Blob,
  filename: string
): Promise<"clipboard" | "download"> {
  if (
    typeof navigator !== "undefined" &&
    "clipboard" in navigator &&
    typeof (window as Window & { ClipboardItem?: typeof ClipboardItem })
      .ClipboardItem === "function"
  ) {
    try {
      // eslint-disable-next-line @typescript-eslint/no-explicit-any
      const ClipboardItemCtor = (window as any).ClipboardItem;
      await navigator.clipboard.write([
        new ClipboardItemCtor({ "image/png": blob }),
      ]);
      return "clipboard";
    } catch {
      /* fall through */
    }
  }
  // Fallback: download
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  a.remove();
  setTimeout(() => URL.revokeObjectURL(url), 1000);
  return "download";
}
